const {
  ASR_SERVER_NODE,
  ASR_MONGO_DATABASE,
  REDIS_HOST,
  REDIS_PORT,
  REDIS_PASSWORD,
  ASR_AUTH_KEY,
  ASR_URL,
} = process.env;

module.exports = {
  ASR_SERVER_NODE,
  ASR_MONGO_DATABASE,
  REDIS_HOST,
  REDIS_PORT,
  REDIS_PASSWORD,
  ASR_AUTH_KEY,
  ASR_URL,
};