const {
  ASR_SERVER_NODE,
  ASR_MONGO_DATABASE,
  REDIS_HOST,
  REDIS_PORT,
  REDIS_PASSWORD,
  UPLOAD_AUTH_KEY,

  UPLOAD_DATA_DOMAIN,
} = process.env;

module.exports = {
  ASR_SERVER_NODE,
  ASR_MONGO_DATABASE,
  REDIS_HOST,
  REDIS_PORT,
  REDIS_PASSWORD,
  UPLOAD_AUTH_KEY,
  UPLOAD_DATA_DOMAIN,
};